### ISSUE TITLE
Incorrect date on startup

### ISSUE THREAD

**Issue by jarikmarwede** [Webierta/calling-plan-control#7]
Every time I open the app it shows "Oct 21, 2021 - Oct 13, 2021".
![IMG_20211013_173118](https://user-images.githubusercontent.com/33765260/137166360-8dad2308-db8d-40f9-82ac-c4fa2d685e22.jpg)
These are my settings:
![IMG_20211013_173742](https://user-images.githubusercontent.com/33765260/137166847-da3d967f-1431-41f4-a32d-950a4177d47b.jpg)
If I click on save, it changes it to the correct date ("Sep 21, 2021 -  Oct 13, 2021"). But it changes back to the incorrect date if I close and open the app again.

**Comment by Webierta** [comment]
Thanks for the info.

I have not been able to reproduce the error you comment. In my case, if I save the data plan start day in Settings, the saved settings are restored correctly after reopening the app.

A suggestion: make sure that after changing the settings, click on the blue Save icon (in the top bar on the right). The settings are not saved if you go back to the main screen with the upper left arrow.

I await your comments.

**Comment by jarikmarwede** [comment]
Well, if I press the blue Save icon it shows the correct data. But if I restart the app it shows the wrong data again. Maybe this is a problem with my phone. But this is the only app that has these problems

**Comment by Webierta** [comment]
OK you are right. I have located the error, when I have a little free time I will fix it.

Thank you very much for notifying it.

**Comment by Webierta** [comment]
Released version 2.1.1 that fixes this bug as of date.
I hope that soon this new version will be published in F-Droid.
I will appreciate your comments on the new version, thank you.

**Comment by jarikmarwede** [comment]
The new version is now on F-Droid and it seems to work perfectly. Thank you very much
